version: '3.8'

services:
  # Seed node - first node in the network
  seed-node:
    build: .
    container_name: zion-seed
    # Environment consolidated below
    volumes:
      - seed-data:/home/zion/.zion
    # Expose only P2P by default; RPC stays internal unless explicitly published
    ports:
      - "18081:18081"  # P2P port
      # - "18080:18080"  # RPC port (disabled by default)
    env_file:
      - .env
    environment:
      - ZION_MODE=seed
      - ZION_LOG_LEVEL=${ZION_LOG_LEVEL:-info}
      - ZION_RPC_BIND=${ZION_RPC_BIND:-127.0.0.1}
      - ZION_RPC_CORS_ORIGINS=${ZION_RPC_CORS_ORIGINS:-}
    networks:
      - zion-seeds
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Pool server
  pool-server:
    build: .
    container_name: zion-pool
    # Environment consolidated below
    volumes:
      - pool-data:/home/zion/.zion
    ports:
      - "3333:3333"    # Pool stratum port
      - "28081:18081"  # P2P port (mapped to different host port)
      # - "28080:18080"  # RPC port (disabled by default)
    env_file:
      - .env
    environment:
      - ZION_MODE=pool
      - ZION_LOG_LEVEL=${ZION_LOG_LEVEL:-info}
      - ZION_RPC_BIND=${ZION_RPC_BIND:-127.0.0.1}
      - ZION_RPC_CORS_ORIGINS=${ZION_RPC_CORS_ORIGINS:-}
      - POOL_PORT=${POOL_PORT:-3333}
      - POOL_DIFFICULTY=${POOL_DIFFICULTY:-1000}
      - POOL_FEE=${POOL_FEE:-1}
      - SEED_NODES=seed-node:18081
    networks:
      - zion-seeds
    depends_on:
      - seed-node
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RPC Shim adapter
  rpc-shim:
    build:
      context: ./adapters/zion-rpc-shim
      dockerfile: Dockerfile
    container_name: zion-rpc-shim
    environment:
      - ZION_RPC_URL=http://seed-node:18081/json_rpc
      - SHIM_PORT=18089
      - GBT_CACHE_MS=8000
    ports:
      - "18089:18089"  # RPC shim port
    networks:
      - zion-seeds
    depends_on:
      - seed-node
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18089/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Miner (optional - comment out if not needed)
  miner:
    build: .
    container_name: zion-miner
    environment:
      - ZION_MODE=miner
      - MINER_POOL=pool-server:3333
      - MINER_THREADS=4
      - MINER_WALLET=YOUR_WALLET_ADDRESS_HERE  # Replace with actual wallet
    networks:
      - zion-seeds
    depends_on:
      - pool-server
    restart: unless-stopped
    profiles:
      - mining  # Only starts when --profile mining is specified

  # Additional full node (optional)
  full-node:
    build: .
    container_name: zion-node
    # Environment consolidated below
    volumes:
      - node-data:/home/zion/.zion
    ports:
      - "38081:18081"  # P2P port (mapped to different host port)
      # - "38080:18080"  # RPC port (disabled by default)
    env_file:
      - .env
    environment:
      - ZION_MODE=daemon
      - ZION_LOG_LEVEL=${ZION_LOG_LEVEL:-info}
      - ZION_RPC_BIND=${ZION_RPC_BIND:-127.0.0.1}
      - ZION_RPC_CORS_ORIGINS=${ZION_RPC_CORS_ORIGINS:-}
      - SEED_NODES=seed-node:18081
    networks:
      - zion-seeds
    depends_on:
      - seed-node
    restart: unless-stopped
    profiles:
      - full  # Only starts when --profile full is specified

volumes:
  seed-data:
    driver: local
  pool-data:
    driver: local
  node-data:
    driver: local

networks:
  zion-seeds:
    external: true