version: '3.8'

services:
  zion-atomic-swap:
    build: 
      context: ./swap-service
      dockerfile: Dockerfile
    container_name: zion-atomic-swap
    restart: unless-stopped
    labels:
      - "description=🔄 Atomic Swap Oracle - Ancient wisdom guides cross-chain exchanges"
      - "cosmic.mantra=Two blockchains unite in cryptographic marriage ceremony!"
      - "oracle.blessing=HTLC protocols echo ancient binding rituals of cosmic trust!"
    ports:
      - "8091:8091"   # Atomic Swap API
    environment:
      - SWAP_PORT=8091
      - ZION_RPC_URL=http://zion-rpc-shim:18089
      - BITCOIN_RPC_URL=http://bitcoind:8332
      - LOG_LEVEL=info
    depends_on:
      zion-rpc-shim:
        condition: service_started
      bitcoind:
        condition: service_started
    networks:
      - zion-lightning
      - zion-internal
    volumes:
      - swap-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Swap Market Maker Bot
  swap-market-maker:
    build:
      context: ./swap-service/market-maker
      dockerfile: Dockerfile
    container_name: zion-swap-market-maker
    restart: unless-stopped
    environment:
      - SWAP_API_URL=http://zion-atomic-swap:8091
      - MARKET_MAKING_ENABLED=true
      - MIN_PROFIT_MARGIN=0.01  # 1% profit margin
      - MAX_SWAP_AMOUNT=1000000 # Max 1M ZION per swap
    depends_on:
      zion-atomic-swap:
        condition: service_healthy
    networks:
      - zion-lightning
    profiles:
      - market-maker  # Optional service

volumes:
  swap-data:
    driver: local

networks:
  zion-lightning:
    external: true
  zion-internal:
    external: true