networks:
  zion-seeds:
    name: zion-seeds
    driver: bridge
    external: true

services:
  seed1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.zion-cryptonote.minimal
    image: zion:production-minimal
    container_name: zion-seed1
    restart: unless-stopped
    # Spuštění bez externího configu – jen CLI parametry
    command: [
      "ziond",
      "--p2p-bind-ip=0.0.0.0",
      "--p2p-bind-port=18080",
      "--rpc-bind-ip=0.0.0.0",
      "--rpc-bind-port=18081",
      "--allow-local-ip",
      "--no-console",
      "--log-level=2"
    ]
    environment:
      - TZ=UTC
    volumes:
      - seed1-data:/home/zion/.zion
    networks:
      zion-seeds:
        aliases:
          - seed1
          - zion-seed1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "curl -f --connect-timeout 3 --max-time 5 http://127.0.0.1:18081/getinfo || curl -f --connect-timeout 3 --max-time 5 http://127.0.0.1:18081/get_info || curl -f --connect-timeout 3 --max-time 5 http://127.0.0.1:18081/json_rpc -d '{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"method\":\"get_info\"}' -H 'Content-Type: application/json'"]
      interval: 15s
      timeout: 8s
      start_period: 180s
      retries: 12
    stop_grace_period: 30s

  seed2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.zion-cryptonote.minimal
    image: zion:production-minimal
    container_name: zion-seed2
    restart: unless-stopped
    # Spuštění bez externího configu; seed2 se připojí na seed1
    command: [
      "ziond",
      "--p2p-bind-ip=0.0.0.0",
      "--p2p-bind-port=18080",
      "--rpc-bind-ip=0.0.0.0",
      "--rpc-bind-port=18081",
      "--allow-local-ip",
      "--no-console",
      "--log-level=2",
      "--seed-node=zion-seed1:18080"
    ]
    environment:
      - TZ=UTC
    volumes:
      - seed2-data:/home/zion/.zion
    depends_on:
      - seed1
    networks:
      zion-seeds:
        aliases:
          - seed2
          - zion-seed2
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "curl -f --connect-timeout 3 --max-time 5 http://127.0.0.1:18081/getinfo || curl -f --connect-timeout 3 --max-time 5 http://127.0.0.1:18081/get_info || curl -f --connect-timeout 3 --max-time 5 http://127.0.0.1:18081/json_rpc -d '{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"method\":\"get_info\"}' -H 'Content-Type: application/json'"]
      interval: 15s
      timeout: 8s
      start_period: 180s
      retries: 12
    stop_grace_period: 30s

  pool:
    image: zion:production-fixed
    container_name: zion-pool
    restart: unless-stopped
    user: "0:0"  # start as root; entrypoint will chown and drop to 'zion' via gosu
    environment:
      - ZION_MODE=daemon
      - ZION_LOG_LEVEL=info
    volumes:
      - pool-data:/home/zion/.zion
    depends_on:
      - seed1
      - seed2
    networks:
      - zion-seeds
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  pool-nodejs:
    build:
      context: ../pool
      dockerfile: Dockerfile
    image: zion:pool-nodejs
    container_name: zion-pool-nodejs
    restart: unless-stopped
    environment:
      - POOL_PORT=3333
      - POOL_BIND=0.0.0.0
    # Port 3333 přebírá Uzi-Pool; stub ponecháváme bez public portu
    networks:
      - zion-seeds
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  rpc-shim:
    build:
      context: ../adapters/zion-rpc-shim
      dockerfile: Dockerfile
    image: zion:rpc-shim
    container_name: zion-rpc-shim
    restart: unless-stopped
    environment:
      - SHIM_PORT=18089
      - ZION_RPC_URLS=http://zion-seed1:18081/json_rpc,http://zion-seed2:18081/json_rpc
      - PREFETCH_WALLET=Z321y5Ugios4VrzgpbGkvoBrmA3QeVC2xao6kY3SDSkA7J8toEUktYzBAYyqQ8SJvP4kAaz1APCBEGRuYWersbCR33tetBoXxg
      - BUSY_CACHE_FACTOR=8
    ports:
      - "18089:18089"  # Monero-like JSON-RPC endpoint for external pool software
    depends_on:
      seed1:
        condition: service_healthy
      seed2:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "node -e 'const s=require(\"net\").Socket(); s.setTimeout(2000); s.on(\"error\",()=>process.exit(1)); s.on(\"timeout\",()=>process.exit(1)); s.connect(18089,\"127.0.0.1\",()=>{s.end(); process.exit(0);});' "]
      interval: 10s
      timeout: 3s
      retries: 5
    stop_grace_period: 20s
    networks:
      - zion-seeds
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  walletd:
    image: zion:production-fixed
    container_name: zion-walletd
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "tr -d '\r' < /config/walletd-entrypoint.sh > /tmp/walletd-entrypoint.sh && chmod +x /tmp/walletd-entrypoint.sh && exec /bin/sh /tmp/walletd-entrypoint.sh"]
    environment:
      - ZION_MODE=walletd
      - WALLET_FILE=/home/zion/.zion/pool.wallet
      - WALLET_PASS=testpass
      - DAEMON_HOST=zion-seed1
      - DAEMON_PORT=18081
      - TZ=UTC
    volumes:
      - wallet-data:/home/zion/.zion
      - ../docker/walletd-entrypoint.sh:/config/walletd-entrypoint.sh:ro
    depends_on:
      - seed1
    networks:
      zion-seeds:
        aliases:
          - walletd
    healthcheck:
      test: ["CMD-SHELL", "curl -sS -X POST -H 'Content-Type: application/json' --connect-timeout 2 --max-time 3 http://127.0.0.1:8070/json_rpc -d '{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"method\":\"getStatus\"}' >/dev/null" ]
      interval: 10s
      timeout: 5s
      retries: 8
    stop_grace_period: 20s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  uzi-pool:
    image: zion:uzi-pool
    container_name: zion-uzi-pool
    restart: unless-stopped
    environment:
      - POOL_CONFIG=/config/config.json
      - COINS_DIR=/config/coins
      - POOL_ADDRESS=Z321y5Ugios4VrzgpbGkvoBrmA3QeVC2xao6kY3SDSkA7J8toEUktYzBAYyqQ8SJvP4kAaz1APCBEGRuYWersbCR33tetBoXxg
      - DEV_ADDRESS=${DEV_ADDRESS:-}
      - CORE_DEV_ADDRESS=${CORE_DEV_ADDRESS:-}
    volumes:
      - ../adapters/uzi-pool-config:/config:ro
    depends_on:
      redis:
        condition: service_healthy
      rpc-shim:
        condition: service_healthy
    ports:
      - "3333:3333"
    networks:
      - zion-seeds
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3333"]
      interval: 15s
      timeout: 5s
      retries: 6
    stop_grace_period: 15s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  wallet-adapter:
    build:
      context: ../adapters/wallet-adapter
      dockerfile: Dockerfile
    image: zion:wallet-adapter
    container_name: zion-wallet-adapter
    restart: unless-stopped
    environment:
      - ADAPTER_PORT=18099
      - ADAPTER_BIND=0.0.0.0
      - WALLET_RPC=http://walletd:8070/json_rpc
      - SHIM_RPC=http://zion-rpc-shim:18089/json_rpc
      - LOG_LEVEL=info
      - CORS_ORIGINS=*
      - TZ=UTC
    ports:
      - "18099:18099"
    depends_on:
      walletd:
        condition: service_healthy
      rpc-shim:
        condition: service_healthy
    networks:
      - zion-seeds
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:18099/healthz >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 6
    stop_grace_period: 15s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:6-alpine
    container_name: zion-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "6379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      zion-seeds:
        aliases:
          - redis
    stop_grace_period: 10s
    environment:
      - TZ=UTC
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  seed1-data:
    driver: local
  seed2-data:
    driver: local
  pool-data:
    driver: local
  wallet-data:
    driver: local
