# ZION Mining Stack - Production Ready Compose
# Updated with correct network aliases and absolute paths for SSH deployment

networks:
  zion-seeds:
    name: zion-seeds
    driver: bridge
    external: true

services:
  # Fixed for production deployment with absolute paths and network aliases
  # Network alias 'rpc-shim' ensures pool can find the service correctly
  rpc-shim:
    image: zion:rpc-shim
    container_name: zion-rpc-shim
    restart: unless-stopped
    environment:
      - SHIM_PORT=18089
      - ZION_RPC_URLS=http://zion-seed1:18081/json_rpc,http://zion-seed2:18081/json_rpc
      - PREFETCH_WALLET=Z3222ywic7fGUZHv9EfFwEKf1VJRrEqPbLrHgRiBb43LWaS1Cz2gVwgdF2kvUPsGb9jSvUUf31oNCSZgNEtUiGDT4sBLtXmGzc
      - BUSY_CACHE_FACTOR=8
      - GBT_CACHE_MS=1500
      - GBT_DISABLE_CACHE_AFTER_HEIGHT=80
      - SUBMIT_INITIAL_DELAY_MS=800
      - SUBMIT_MAX_BACKOFF_MS=12000
      - PREFETCH_INTERVAL_MS=4000
      - PREFETCH_RESERVE=24
    ports:
      - "18089:18089"
    networks:
      zion-seeds:
        aliases:
          - rpc-shim
    healthcheck:
      test: ["CMD-SHELL", "node -e 'const s=require(\"net\").Socket(); s.setTimeout(2000); s.on(\"error\",()=>process.exit(1)); s.on(\"timeout\",()=>process.exit(1)); s.connect(18089,\"127.0.0.1\",()=>{s.end(); process.exit(0);});' "]
      interval: 10s
      timeout: 3s
      retries: 5

  uzi-pool:
    image: zion:uzi-pool
    container_name: zion-uzi-pool
    restart: unless-stopped
    environment:
      - POOL_ADDRESS=Z3222ywic7fGUZHv9EfFwEKf1VJRrEqPbLrHgRiBb43LWaS1Cz2gVwgdF2kvUPsGb9jSvUUf31oNCSZgNEtUiGDT4sBLtXmGzc
      - DAEMON_HOST=rpc-shim
      - DAEMON_PORT=18089
      - REDIS_HOST=zion-redis
      - REDIS_PORT=6379
      - COINS_DIR=/config/coins
    ports:
      - "3333:3333"
    volumes:
      # Update this path for your deployment location
      - /media/maitreya/ZION1/adapters/uzi-pool-config:/config:ro
    depends_on:
      - rpc-shim
      - redis
    networks:
      - zion-seeds
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3333"]
      interval: 15s
      timeout: 5s
      retries: 3

  redis:
    image: redis:6-alpine
    container_name: zion-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - zion-seeds
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3